export const COACHES = [
  {
    id: 5,
    slug: 'saurabh-sharda',
    name: 'Saurabh Sharda',
    title: 'Personality Development Coach',
    rating: 5.0,
    reviews: 312,
    tags: ['Personality Development', 'Communication', 'Leadership', 'Self-Confidence'],
    price: '₹1200/hr',
    priceValue: 1200,
    image: '/images/saurabh.jpg',
    experience: '15+ Years Experience',
    bio: 'A Youth Personality Development Entrepreneur with 15+ years of entrepreneurial experience. I blend my practical knowledge with theoretical insights to empower students with life skills that go beyond conventional education. Now, I’m here to share my expertise in building self-confidence, mastering communication, and developing leadership qualities through a transformative Personality Development Masterclass.',
    email: 'saurabh.sharda@example.com',
    calcomLink: 'rick/15min',
  },
  {
    id: 1,
    slug: 'sarah-jenkins',
    name: 'Sarah Jenkins',
    title: 'Ex-Google Engineering Manager',
    rating: 4.9,
    reviews: 124,
    tags: ['Software Engineering', 'System Design', 'Leadership'],
    price: '₹3500/hr',
    priceValue: 3500,
    image: 'https://i.pravatar.cc/150?u=sarah',
    bio: 'I help software engineers transition to senior and lead roles. Specializing in system design and behavioral interviews.',
    email: 'sarah.jenkins.interviewace@gmail.com', // Hidden from frontend
    calcomLink: 'rick/15min',
  },
  {
    id: 2,
    slug: 'david-chen',
    name: 'David Chen',
    title: 'Senior Product Manager at Meta',
    rating: 4.8,
    reviews: 89,
    tags: ['Product Management', 'Strategy', 'Behavioral'],
    price: '₹2800/hr',
    priceValue: 2800,
    image: 'https://i.pravatar.cc/150?u=david',
    bio: 'Product sense and execution interviews are my bread and butter. Let\'s get you that PM offer.',
    email: 'david.chen.interviewace@gmail.com',
    calcomLink: 'rick/15min',
  },
  {
    id: 3,
    slug: 'elena-rodriguez',
    name: 'Elena Rodriguez',
    title: 'Communication & Career Coach',
    rating: 5.0,
    reviews: 210,
    tags: ['Communication', 'Salary Negotiation', 'Confidence'],
    price: '₹2000/hr',
    priceValue: 2000,
    image: 'https://i.pravatar.cc/150?u=elena',
    bio: 'Master the art of storytelling in interviews. I will help you build confidence and negotiate top-tier compensation.',
    email: 'elena.rodriguez.interviewace@gmail.com',
    calcomLink: 'rick/15min',
  },
  {
    id: 4,
    slug: 'michael-chang',
    name: 'Michael Chang',
    title: 'Quant & Finance Expert',
    rating: 4.7,
    reviews: 56,
    tags: ['Finance', 'Quantitative Analysis', 'Brain Teasers'],
    price: '₹4200/hr',
    priceValue: 4200,
    image: 'https://i.pravatar.cc/150?u=michael',
    bio: 'Ex-Jane Street trader helping aspiring quants ace probability, brainteasers, and technical math interviews.',
    email: 'michael.chang.interviewace@gmail.com',
    calcomLink: 'rick/15min',
  },
  {
    id: 6,
    slug: 'ankit-kumar',
    name: 'Ankit Kumar',
    title: 'Generative AI & Agentic AI Expert',
    rating: 5.0,
    reviews: 142,
    tags: ['Generative AI', 'Agentic AI', 'LLMs', 'System Design'],
    price: '₹1500/hr',
    priceValue: 1500,
    image: '/images/ankit.jpg',
    experience: 'AI Specialist',
    bio: 'I specialize in Generative AI and Agentic AI systems. I will help you master LLM architectures, AI agents, and system design for modern AI applications to ace your next AI engineering interview.',
    email: 'ankit.kumar@interviewace.ai',
    calcomLink: 'ankit-kumar-academy/15min',
  }
];
