export const COACHES = [
  {
    id: 5,
    slug: 'saurabh-sharda',
    name: 'Saurabh Sharda',
    title: 'Personality Development Coach',
    rating: 5.0,
    reviews: 312,
    tags: ['Personality Development', 'Communication', 'Leadership', 'Self-Confidence'],
    price: '₹1200/hr',
    priceValue: 1200,
    image: '/images/saurabh.jpg',
    experience: '15+ Years Experience',
    bio: 'A Youth Personality Development Entrepreneur with 15+ years of entrepreneurial experience. I blend my practical knowledge with theoretical insights to empower students with life skills that go beyond conventional education. Now, I’m here to share my expertise in building self-confidence, mastering communication, and developing leadership qualities through a transformative Personality Development Masterclass.',
    email: 'saurabh.sharda@example.com',
    calcomLink: 'rick/15min',
  },
  {
    id: 6,
    slug: 'ankit-kumar',
    name: 'Ankit Kumar',
    title: 'Generative AI & Agentic AI Expert',
    rating: 5.0,
    reviews: 142,
    tags: ['Generative AI', 'Agentic AI', 'LLMs', 'System Design'],
    price: '₹1500/hr',
    priceValue: 1500,
    image: '/images/ankit.jpg',
    experience: 'AI Specialist',
    bio: 'I specialize in Generative AI and Agentic AI systems. I will help you master LLM architectures, AI agents, and system design for modern AI applications to ace your next AI engineering interview.',
    email: 'ankit.kumar@interviewace.ai',
    calcomLink: 'ankit-kumar-academy/15min',
  },
];
